"""insert_friends

Revision ID: cac7975449dd
Revises: 64ba34349b95
Create Date: 2021-01-12 09:33:01.626077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac7975449dd'
down_revision = '64ba34349b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.alter_column('problem_types', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problems', 'problem_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user_plans', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_plans', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user_plans')
    # op.drop_constraint(None, 'user_plans', type_='foreignkey')
    # op.drop_constraint(None, 'user_plans', type_='foreignkey')
    op.alter_column('problems', 'problem_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('problem_types', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('friends')
    # ### end Alembic commands ###
