"""Initial migration.

Revision ID: 5b2ae6c9339b
Revises: ffdc0a98111c
Create Date: 2021-01-06 10:22:46.777958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2ae6c9339b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_route', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avy_observations', sa.String(length=500), nullable=True),
    sa.Column('snowpack_summary', sa.String(length=500), nullable=True),
    sa.Column('temp_now', sa.Integer(), nullable=True),
    sa.Column('wind_sp_now', sa.Integer(), nullable=True),
    sa.Column('wind_dir_now', sa.String(length=50), nullable=True),
    sa.Column('sky_cover_now', sa.String(length=50), nullable=True),
    sa.Column('precip_now', sa.String(length=150), nullable=True),
    sa.Column('temp_fore', sa.Integer(), nullable=True),
    sa.Column('wind_sp_fore', sa.Integer(), nullable=True),
    sa.Column('wind_dir_fore', sa.String(length=50), nullable=True),
    sa.Column('sky_cover_fore', sa.String(length=50), nullable=True),
    sa.Column('precip_fore', sa.String(length=150), nullable=True),
    sa.Column('weather_contribution', sa.String(length=255), nullable=True),
    sa.Column('weather_summary', sa.String(length=255), nullable=True),
    sa.Column('ates', sa.String(length=50), nullable=True),
    sa.Column('terrain_avoiding', sa.String(length=150), nullable=True),
    sa.Column('obs_fore_summary', sa.String(length=255), nullable=True),
    sa.Column('mindset', sa.String(length=150), nullable=True),
    sa.Column('tour_plan', sa.String(length=1000), nullable=True),
    sa.Column('emergency_plan', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('plans.id', sa.Integer(), nullable=False),
    sa.Column('users.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plans.id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users.id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'plans.id', 'users.id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('route_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aspect', sa.String(length=50), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('danger_rating', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('likelihood', sa.String(length=50), nullable=False),
    sa.Column('weak_layer', sa.String(length=50), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.add_column('users', sa.Column('avy_edu', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avy_edu')
    op.drop_table('problems')
    op.drop_table('plans')
    op.drop_table('routes')
    # ### end Alembic commands ###
